name: "NestJS Controller File Finder"
description: "Find modified NestJS controllers and update API Gateway"

runs:
  using: docker
  image: docker://yalm/nestjs-controller-file-finder:0.0.1

branding:
  icon: search
  color: blue