name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true
      - name: Run build
        run: |
          mkdir -p build
          go build -ldflags="-w -s" -o ./build ./src
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
          GOFLAGS: -buildvcs=false
      - name: Build Docker Image
        run: docker build . --tag nestjs-controller-file-finder:latest
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: yalm/nestjs-controller-file-finder
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
