name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true
      - name: Run build
        run: |
          mkdir -p build
          go build -ldflags="-w -s" -o ./build ./src
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
          GOFLAGS: -buildvcs=false
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/**